const TOKEN=localStorage.getItem('sai_token');
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
if(!TOKEN){location.href='./';}
function api(path,opt={}){const h=opt.headers||{};h.Authorization=`Bearer ${TOKEN}`;if(!(opt.body instanceof FormData))h['Content-Type']='application/json';return fetch(`/api${path}`,{...opt,headers:h}).then(async r=>{const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||'Request failed');return d})}
function notice(msg,error=false){const n=$('#notice');n.textContent=msg;n.className='notice'+(error?' error':'');setTimeout(()=>n.classList.add('hidden'),4000)}
const titles={dashboard:['Dashboard','Business overview and system health'],members:['Members','Excel customer database and membership status'],campaigns:['Campaigns','In-app business broadcast and campaign history'],ai:['AI Calling','Scripts, consent-ready queue and call jobs'],users:['Users & Roles','Owner-controlled access management'],activity:['Activity','Recent owner activity']};
function showSection(id){$$('.section').forEach(x=>x.classList.toggle('active',x.id===id));$$('.nav').forEach(x=>x.classList.toggle('active',x.dataset.section===id));$('#section-title').textContent=titles[id][0];$('#section-sub').textContent=titles[id][1]; if(id==='dashboard')loadDashboard();if(id==='members')loadMembers();if(id==='campaigns')loadCampaigns();if(id==='ai')loadAI();if(id==='users')loadUsers();if(id==='activity')loadActivity();}
$$('.nav').forEach(b=>b.onclick=()=>showSection(b.dataset.section));$$('[data-go]').forEach(b=>b.onclick=()=>showSection(b.dataset.go));$('#logout').onclick=()=>{localStorage.removeItem('sai_token');location.href='./'};
async function loadDashboard(){try{const d=await api('/owner/overview');$('#stats').innerHTML=Object.entries({Members:d.counts.total,Valid:d.counts.valid,Expired:d.counts.expired,'New':d.counts.new,'AI Queue':d.jobs.queued}).map(([k,v])=>`<div class="stat"><span>${k}</span><strong>${v}</strong></div>`).join('');$('#health').innerHTML='<span class="badge valid">API ONLINE</span> &nbsp; Demo mode supported';}catch(e){notice(e.message,true)}}
function badge(s){return `<span class="badge ${s}">${s.toUpperCase()}</span>`}
async function loadMembers(){try{const q=encodeURIComponent($('#member-search').value||'');const st=$('#member-status').value;const d=await api(`/owner/contacts?q=${q}&status=${st}`);$('#member-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Phone</th><th>Status</th><th>Expiry</th><th>Group</th><th>Opt-in</th></tr></thead><tbody>${d.contacts.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.phone)}</td><td>${badge(c.computedStatus)}</td><td>${esc(c.expiryDate||'-')}</td><td>${esc(c.group||'-')}</td><td>${c.optIn?'Yes':'No'}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No members found</td></tr>'}</tbody></table></div>`}catch(e){notice(e.message,true)}}
$('#member-search').oninput=loadMembers;$('#member-status').onchange=loadMembers;
$('#excel').onchange=async e=>{const f=e.target.files[0];if(!f)return;const fd=new FormData();fd.append('file',f);try{const d=await api('/owner/import-xlsx',{method:'POST',body:fd});notice(`Imported: ${d.added} added, ${d.updated} updated, ${d.skipped} skipped`);loadMembers();loadDashboard()}catch(err){notice(err.message,true)}e.target.value=''};
async function loadCampaigns(){try{const d=await api('/marketing/campaigns');$('#campaign-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Audience</th><th>Status</th><th>Total</th><th>Sent</th><th>Action</th></tr></thead><tbody>${d.campaigns.map(c=>`<tr><td>${esc(c.name)}</td><td>${esc(c.group)}</td><td>${esc(c.status)}</td><td>${c.stats.total}</td><td>${c.stats.sent}</td><td>${c.status==='draft'?`<button class="btn" onclick="sendCamp('${c.id}')">Send In-App</button>`:''}</td></tr>`).join('')||'<tr><td colspan="6" class="muted">No campaigns yet</td></tr>'}</tbody></table></div>`}catch(e){notice(e.message,true)}}
window.sendCamp=async id=>{try{const d=await api(`/marketing/campaigns/${id}/send-internal`,{method:'POST',body:'{}'});notice(`Sent to ${d.result.sent} app users; skipped ${d.result.skipped}`);loadCampaigns()}catch(e){notice(e.message,true)}};
$('#create-camp').onclick=async()=>{try{const d=await api('/marketing/campaigns',{method:'POST',body:JSON.stringify({name:$('#camp-name').value,message:$('#camp-message').value,group:$('#camp-group').value})});notice(`Campaign created: ${d.campaign.name}`);$('#camp-name').value='';$('#camp-message').value='';loadCampaigns()}catch(e){notice(e.message,true)}};
async function loadAI(){try{const [s,j]=await Promise.all([api('/owner/scripts'),api('/owner/ai-calls/jobs')]);$('#ai-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Script</th><th>Match</th><th>Enabled</th><th>Queue Jobs</th></tr></thead><tbody>${s.scripts.map(x=>`<tr><td>${esc(x.name)}</td><td>${badge(x.matchStatus)}</td><td>${x.enabled?'Yes':'No'}</td><td>${j.jobs.filter(z=>z.scriptId===x.id).length}</td></tr>`).join('')||'<tr><td colspan="4" class="muted">No scripts yet</td></tr>'}</tbody></table></div>`}catch(e){notice(e.message,true)}}
$('#create-script').onclick=async()=>{try{await api('/owner/scripts',{method:'POST',body:JSON.stringify({name:$('#script-name').value,matchStatus:$('#script-status').value,script:$('#script-text').value})});notice('AI script saved');$('#script-name').value='';$('#script-text').value='';loadAI()}catch(e){notice(e.message,true)}};
$('#auto-queue').onclick=async()=>{try{const d=await api('/owner/ai-calls/auto-queue',{method:'POST',body:'{}'});notice(`${d.queued} calls queued`);loadAI();loadDashboard()}catch(e){notice(e.message,true)}};
async function loadUsers(){try{const d=await api('/business/users');$('#users-table').innerHTML=`<div class="table-wrap"><table class="table"><thead><tr><th>Name</th><th>Username</th><th>Phone</th><th>Role</th><th>Change</th></tr></thead><tbody>${d.users.map(u=>`<tr><td>${esc(u.name)}</td><td>${esc(u.username)}</td><td>${esc(u.phone)}</td><td>${esc(u.role)}</td><td>${u.role==='owner'?'Owner':`<select onchange="roleChange('${u.id}',this.value)"><option ${u.role==='user'?'selected':''}>user</option><option ${u.role==='manager'?'selected':''}>manager</option><option ${u.role==='admin'?'selected':''}>admin</option></select>`}</td></tr>`).join('')}</tbody></table></div>`}catch(e){notice(e.message,true)}}
window.roleChange=async(id,role)=>{try{await api(`/business/users/${id}`,{method:'PATCH',body:JSON.stringify({role})});notice('Role updated');loadUsers()}catch(e){notice(e.message,true)}};
async function loadActivity(){try{const d=await api('/owner/overview');$('#activity-table').innerHTML='<p class="muted">Activity audit is stored by the backend. The full log viewer can be expanded as the next module.</p><pre>'+JSON.stringify(d,null,2)+'</pre>'}catch(e){notice(e.message,true)}}
function esc(v){return String(v??'').replace(/[&<>"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[m]))}
showSection('dashboard');
